# Generated by Django 4.2.1 on 2023-06-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_meter_tariff_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_number',
            field=models.CharField(blank=True, default='CZ', max_length=10),
        ),
    ]
