# Generated by Django 4.2.1 on 2023-06-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_member_member_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='member',
        ),
        migrations.AddField(
            model_name='invoice',
            name='meter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.meter'),
        ),
    ]
